### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by skrimxyz** [daccakareem/qb-spawnselector-np#1]
I did what it say's in the readme but it's not working

**Comment by krrm1** [comment]
you need spawn stream

**Comment by krrm1** [comment]
set name to qb-spawnselector

**Comment by skrimxyz** [comment]
> set name to qb-spawnselector

still not working

**Comment by AndreasFromDanmark** [comment]
Same here not working

**Comment by krrm1** [comment]
for me working good

**Comment by krrm1** [comment]
i dont know if they update there script but  i upload new one go check it out
